<a href="https://colab.research.google.com/github/Kei300/IA-Python-Libraries-Statistics/blob/main/6_Probabilidad_Meteorol%C3%B3gica_Estaci%C3%B3n_Fes_Aragon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Probabilidad Meteorológica Estación FES Aragón

In [114]:
import pandas as pd

In [115]:
path = "/content/meteorologia_2025.csv"
df_temp = pd.read_csv(
    path,
    sep=',',
    skiprows=9,
    header=0,
    low_memory=False
)

df = df_temp.rename(columns={'valor': 'value'}).drop(columns=['unit'])
df.columns = ['datetime', 'station_id', 'variable', 'value']
print("Filas cargadas:", len(df))

Filas cargadas: 1191360

In [116]:
df['value'] = pd.to_numeric(df['value'], errors='coerce')

df_pivot = df.pivot_table(
    index=['datetime', 'station_id'],
    columns='variable',
    values='value',
    aggfunc='first'
).reset_index()

df_pivot.columns.name = None

display(df_pivot.head())

              datetime station_id    RH  TMP    WDR  WSP
0  2025-01-01 00:00:00        ACO  28.0  8.7    2.0  2.4
1  2025-01-01 00:00:00        AJM  34.0  9.6  221.0  4.2
2  2025-01-01 00:00:00        AJU  74.0  1.5    NaN  NaN
3  2025-01-01 00:00:00        CHO  40.0  NaN    NaN  NaN
4  2025-01-01 00:00:00        CUA   NaN  NaN  245.0  1.3

In [117]:
df_estacion = df_pivot[df_pivot["station_id"] == 'FAR'].copy()
df_estacion = df_estacion.dropna(subset=["RH", "WSP"])

total_registros = len(df_estacion)
print(f"Registros válidos: {total_registros}")
display(df_estacion.head())

Registros válidos: 6556

                  datetime station_id    RH   TMP    WDR  WSP
16147  2025-01-31 00:00:00        FAR  45.0  16.6  141.0  1.1
16170  2025-01-31 01:00:00        FAR  54.0  14.5  134.0  1.4
16193  2025-01-31 02:00:00        FAR  59.0  12.6   79.0  1.4
16216  2025-01-31 03:00:00        FAR  61.0  11.9   87.0  1.4
16239  2025-01-31 04:00:00        FAR  61.0  11.2   68.0  0.8

In [118]:
cond_hum_alta = df_estacion["RH"] >= 70
cond_viento_tranq = df_estacion["WSP"] <= 1

a) Probabilidad de humedad alta ($ \ge 70$)

In [119]:
p_hum_alta = cond_hum_alta.sum() / total_registros

b) Probabilidad de viento tranquilo ($ \le 1$)

In [120]:
p_viento_tranq = cond_viento_tranq.sum() / total_registros

c) $P(\text{humedad_alta} \mid \text{viento_tranquilo})$

In [121]:
ambos = (cond_hum_alta & cond_viento_tranq).sum()
p_hum_dado_viento = ambos / cond_viento_tranq.sum()

d) $P(\text{viento_tranquilo} \mid \text{humedad_alta})$

In [122]:
p_viento_dado_hum = ambos / cond_hum_alta.sum()

In [123]:
print(f"a) P(Humedad Alta): {p_hum_alta:.4f}")
print(f"b) P(Viento Tranquilo): {p_viento_tranq:.4f}")
print(f"c) P(Humedad Alta | Viento Tranquilo): {p_hum_dado_viento:.4f}")
print(f"d) P(Viento Tranquilo | Humedad Alta): {p_viento_dado_hum:.4f}")

a) P(Humedad Alta): 0.3162
b) P(Viento Tranquilo): 0.1138
c) P(Humedad Alta | Viento Tranquilo): 0.6609
d) P(Viento Tranquilo | Humedad Alta): 0.2378